library(PNADcIBGE)
library(survey)
library(dplyr)

year - ano
quarter - trimestre
labels - valores textuais
deflator - inflação
design - desenho amostral
savedir - 

```{r}
dados_pnadc <- get_pnadc(year=2023, quarter=1, 
                         labels=TRUE, deflator=TRUE, 
                         design=TRUE, savedir=tempdir())
```
```{r}
dados_pnadc_brutos <- get_pnadc(year=2023, quarter=1, 
                         labels=TRUE, deflator=TRUE, 
                         design=FALSE, savedir=tempdir())
```


```{r}
dados_pessoas_ocupadas_e_sexo <- get_pnadc(year = 2023, quarter = 1, vars = c("VD4002", "VD4002"))
```
```{r}

```


```{r}
rm()
```

```{r}

```


=-=-=-=-=-= QUESTÃO 02 =-=-=-=-=-=

```{r}
soma_divisao_por_2 <- function(a, b) {
  resultado <- (a + b) / 2
  return(resultado)
}

soma_divisao_por_2(3, 2)
```

3
a
```{r}
media <- 90
desvio_padrao <- 10
limite <- 100

probabilidade <- 1 - pnorm(limite, mean = media, sd = desvio_padrao)
probabilidade
```

b
```{r}
media <- 10
variancia <- 36
limite <- 5

desvio_padrao <- sqrt(variancia)

probabilidade <- pnorm(limite, mean = media, sd = desvio_padrao, lower.tail = FALSE)
probabilidade
```

c
```{r}
media <- 10
variancia <- 36
limite_inferior <- 4
limite_superior <- 16

desvio_padrao <- sqrt(variancia)

probabilidade_inferior <- pnorm(limite_inferior, mean = media, sd = desvio_padrao)
probabilidade_superior <- pnorm(limite_superior, mean = media, sd = desvio_padrao)

probabilidade <- probabilidade_superior - probabilidade_inferior
probabilidade
```


4

```{r}
media <- 45
desvio_padrao <- 12
total_compradores <- 200
```

a
```{r}
# Entre 24 e 54 minutos
limite_inferior_a <- 24
limite_superior_a <- 54

probabilidade_a <- pnorm(limite_superior_a, mean = media, sd = desvio_padrao) - pnorm(limite_inferior_a, mean = media, sd = desvio_padrao)
compradores_esperados_a <- probabilidade_a * total_compradores

print(probabilidade_a)
print(compradores_esperados_a)
```


b
```{r}
# Mais de 39 minutos
limite_superior_b <- 39

probabilidade_b <- 1 - pnorm(limite_superior_b, mean = media, sd = desvio_padrao)
compradores_esperados_b <- probabilidade_b * total_compradores

print(probabilidade_b)
print(compradores_esperados_b)
```


Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.
